config/routes.rb
Rails.application.routes.draw do
  resources :portraits
  resources :members
  resources :groups
  resources :projects
  resources :people
  get 'welcome/index'

  get 'welcome/ineex'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portrait.rb
class Portrait < ApplicationRecord
  belongs_to :person
end

app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  before_action :set_portrait, only: [:show, :edit, :update, :destroy]

  # GET /portraits
  # GET /portraits.json
  def index
    @portraits = Portrait.all
  end

  # GET /portraits/1
  # GET /portraits/1.json
  def show
  end

  # GET /portraits/new
  def new
    @portrait = Portrait.new
  end

  # GET /portraits/1/edit
  def edit
  end

  # POST /portraits
  # POST /portraits.json
  def create
    @portrait = Portrait.new(portrait_params)

    respond_to do |format|
      if @portrait.save
        format.html { redirect_to @portrait, notice: 'Portrait was successfully created.' }
        format.json { render :show, status: :created, location: @portrait }
      else
        format.html { render :new }
        format.json { render json: @portrait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portraits/1
  # PATCH/PUT /portraits/1.json
  def update
    respond_to do |format|
      if @portrait.update(portrait_params)
        format.html { redirect_to @portrait, notice: 'Portrait was successfully updated.' }
        format.json { render :show, status: :ok, location: @portrait }
      else
        format.html { render :edit }
        format.json { render json: @portrait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portraits/1
  # DELETE /portraits/1.json
  def destroy
    @portrait.destroy
    respond_to do |format|
      format.html { redirect_to portraits_url, notice: 'Portrait was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portrait
      @portrait = Portrait.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portrait_params
      params.require(:portrait).permit(:level, :image, :person_id)
    end
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/views/portraits/_form.html.erb
<%= form_for(portrait) do |f| %>
  <% if portrait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portrait.errors.count, "error") %> prohibited this portrait from being saved:</h2>

      <ul>
      <% portrait.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level, id: :portrait_level %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image, id: :portrait_image %>
  </div>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.number_field :person_id, id: :portrait_person_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portraits/edit.html.erb
<h1>Editing Portrait</h1>

<%= render 'form', portrait: @portrait %>

<%= link_to 'Show', @portrait %> |
<%= link_to 'Back', portraits_path %>

app/views/portraits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Portraits</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Image</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portraits.each do |portrait| %>
      <tr>
        <td><%= portrait.level %></td>
        <td><%= portrait.image %></td>
        <td><%= portrait.person_id %></td>
        <td><%= link_to 'Show', portrait %></td>
        <td><%= link_to 'Edit', edit_portrait_path(portrait) %></td>
        <td><%= link_to 'Destroy', portrait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portrait', new_portrait_path %>

app/views/portraits/new.html.erb
<h1>New Portrait</h1>

<%= render 'form', portrait: @portrait %>

<%= link_to 'Back', portraits_path %>

app/views/portraits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <string>Level:</string>
  <%= @portrait.level %>
</p>

<p>
  <string>Image:</string>
  <%= @portrait.image %>
</p>

<p>
  <string>Person:</string>
  <%= @portrait.person_id %>
</p>

<%= link_to 'Edit', edit_portrait_path(@portrait) %> |
<%= link_to 'Back', portraits_path %>